# Generated by Django 5.0 on 2024-01-13 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsverification',
            name='slug',
            field=models.SlugField(default='', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be True', regex='^\\+998([- ])?(90|91|93|94|95|98|99|33|97|71|88|97)([- ])?(\\d{3})([- ])?(\\d{2})([- ])?(\\d{2})$')]),
        ),
    ]
